name: flutter_english_course
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # Added for tutorial 1
  google_fonts: ^6.2.1
  go_router: ^15.1.1
  badges: ^3.1.2

  # Added for tutorial 2
  ionicons: ^0.2.2
  flutter_svg: ^2.1.0
  step_progress_indicator: ^1.0.2
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1
  intl: ^0.20.2
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/lottie/

  fonts:
    - family: EnliveIcons
      fonts:
        - asset: assets/fonts/EnliveIcons.ttf